version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    container_name: chat-backend
    networks:
      - chat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
    container_name: chat-frontend
    depends_on:
      - backend
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge