version: '4.0'

services:
  database:
    restart: always
    image: postgres:latest
    container_name: chat-app-db
    env_file:
      - postgres.env
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - "5432:5432"
    volumes:
      - ./volume:/var/lib/data/postgresql
    networks:
      - chat-network


networks:
  chat-network:
    driver: bridge